export const doctors = [
  {
    id: 1,
    name: 'Dr Vandana Narula',
    speciality: 'OBGYN Expert',
    image: '/images/dr-vandana-narula.jpeg',
    bio: 'Infertility & cosmetic gynecology expert with 35+ years of experience, providing compassionate, world-class care for women across every stage of life.',
    qualifications: ['MD OBGYN', 'FICOG', 'CIMP'],
    experience: '35+ years',
    experienceHighlights: [
      '35+ years of OBGYN, infertility treatment & cosmetic gynecology',
      'Consultant at Fortis, Artemis, W Pratiksha, CK Birla, Neelkanth Hospitals (Gurgaon)',
      'Former senior resident at Safdarjung hospital & Holy family hospital (New Delhi)',
    ],
    achievements: [
      'Past President, Gurgaon Obs & Gynae Society',
      'Former Chapter Secretary, Indian Menopause Society (Gurgaon)',
      'Chairperson, Digital Web Committee (IMS)',
      'Past President, IMA Gurgaon',
      'SAFOMS member (present) since 2019',
    ],
  },
  {
    id: 2,
    name: 'Dr Sanjay Narula',
    speciality: 'General Surgeon & Medico-legal expert',
    image: '/images/dr-milind.jpg',
    bio: 'General surgeon with a patient-first approach and expertise in medicolegal cases—known for clear guidance, surgical excellence, and dependable recovery support.',
    qualifications: ['MS Surgery (PGI Rohtak)'],
    experience: '35+ years',
    experienceHighlights: [
      'Posted at civil hospital Gurgaon as surgeon for 35 years',
      'Post-PG experience at PGIMS Rohtak and Batra Hospital (Delhi)',
      'Known for clear understanding of options and recovery partnership',
    ],
    achievements: [
      'Chairman, Medical Negligence Board (Gurgaon) for 15 years',
      'Awarded on Republic Day for drafting Disaster Management Plan of Gurgaon',
      'Only medical member of the State Crisis Committee of Haryana (past)',
      'Contributing author of national patient safety guidelines (MoHFW, Govt. of India)',
      'Performed 80,000+ lap tubectomies during service',
      'Appreciation award by Association of Surgeons of India for organizing ASICON',
    ],
  },
  {
    id: 3,
    name: 'Dr Sidhant Narula',
    speciality: 'Bone & Joint Specialist',
    image: '/images/dr-sidhant.jpg',
    bio: 'Orthopaedic specialist focused on joint replacement, rehabilitation, trauma, and sports injuries—bringing precision and a patient-centred approach.',
    qualifications: ['MS Orthopaedics (UCMS)', 'Fellowship in Bone & Joint Replacement'],
    experience: '10+ years',
    experienceHighlights: [
      'Consultant in Max Dwarka joint replacement team',
      'Visiting consultant at BLK, Pushpanjali, and Chiranjivi Hospitals (Gurgaon)',
      'Former senior resident at GTB Hospital (New Delhi)',
    ],
    achievements: [
      'Fellowship in Bone & Joint Replacement (Sarvodaya Hospital, Faridabad)',
      'Mentored clinical excellence from MAMC & UCMS (New Delhi)',
    ],
  },
  {
    id: 4,
    name: 'Dr Milind Shinde',
    speciality: 'Consultant Paediatrician & Neonatologist',
    image: "/images/dr-sanjay.jpg",
    bio: 'Paediatrics and neonatology specialist dedicated to the healthiest start—supporting growth, immunizations, and long-term wellness through adolescence.',
    qualifications: ['MD Paediatrics (AIIMS)', 'DNB Paediatrics'],
    experience: '8+ years',
    experienceHighlights: [
      'Over 8 years of experience in Paediatrics & Neonatology',
      'Currently Assistant Professor at Army College of Medical Sciences & Base Hospital (New Delhi)',
      'Former senior resident at Kalawati Saran Children Hospital (2022–2025)',
    ],
    achievements: [
      'Dr J N Pohowala medal (Best postgraduate research paper, 2021)',
      '1st Prize in Paediatric Nephrology quiz (AIIMS Bhopal, 2020)',
      '2nd & 3rd prize in poster and paper presentation (National conclave, 2019)',
      'Certificate for best research work (Clinical & General psychology/pedagogics) by KSMU (2010)',
      'Completed Clinical skills examination recognized by KSMU & Virginia Tech Carilion School of Medicine (USA, 2014)',
    ],
  },
];

export const services = [
  {
    id: 1,
    name: 'Orthopedics',
    icon: '🦴',
    description: 'Comprehensive orthopedic care for joint, bone, and muscle disorders',
    features: [
      'Joint Replacement Surgery',
      'Sports Medicine',
      'Arthroscopic Surgery',
      'Fracture Management',
      'Spine Surgery',
      'Physiotherapy',
    ],
  },
  {
    id: 2,
    name: 'General Surgery',
    icon: '🏥',
    description: 'Comprehensive surgical procedures with expert care',
    features: [
      'Hernia Repair',
      'Appendectomy',
      'Gallbladder Surgery',
      'Thyroid Surgery',
      'Trauma Surgery',
      'Medico-legal Consultations',
    ],
  },
  {
    id: 3,
    name: 'Pediatrics',
    icon: '👶',
    description: 'Specialized healthcare services for infants and children',
    features: [
      'Child Development Assessment',
      'Immunization Programs',
      'Nutrition Counseling',
      'Growth Monitoring',
      'Newborn Care',
      'Pediatric Emergencies',
    ],
  },
  {
    id: 4,
    name: 'Gynecology',
    icon: '❤️',
    description: 'Comprehensive womens health and reproductive services',
    features: [
      'Obstetrics Care',
      'Gynecological Surgery',
      'Reproductive Health',
      'Fertility Assessment',
      'Maternal Health',
      'Wellness Programs',
    ],
  },
  {
    id: 5,
    name: 'Medicolegal Services',
    icon: '⚖️',
    description: 'Partner of KN MEDICOLEGAL SUPPORT — Expert medicolegal consultations and support. Visit: knmedicolegal.com',
    features: [
      'Medical negligence consultation',
      'Training of staff',
      'Audit of medical records',
      'Medicolegal documentation',
      'Expert witness support',
      'Injury assessment',
    ],
  },
  {
    id: 6,
    name: 'Wellness & Prevention',
    icon: '💚',
    description: 'Preventive health programs and wellness services',
    features: [
      'Health Checkup Packages',
      'Vaccination Programs',
      'Nutrition Counseling',
      'Fitness Assessment',
      'Health Screening',
      'Employee Wellness',
    ],
  },
];

export const testimonials = [
  {
    name: 'Rajesh Kumar',
    role: 'Patient',
    message: 'Excellent care and professional service. Dr. Narula and his team made my recovery smooth and comfortable.',
    rating: 5,
  },
  {
    name: 'Priya Singh',
    role: 'Patient',
    message: 'The clinic has state-of-the-art facilities and staff is very cooperative. Highly recommended!',
    rating: 5,
  },
  {
    name: 'Amit Patel',
    role: 'Patient',
    message: 'Best orthopedic care in the city. Very satisfied with the treatment and results.',
    rating: 5,
  },
];
